Reading samples...
0it [00:00, ?it/s]0it [00:00, ?it/s]
Traceback (most recent call last):
  File "/usr/local/bin/evaluate_functional_correctness", line 33, in <module>
    sys.exit(load_entry_point('human-eval', 'console_scripts', 'evaluate_functional_correctness')())
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/bin/evaluate_functional_correctness", line 25, in importlib_load_entry_point
    return next(matches).load()
           ^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/metadata/__init__.py", line 205, in load
    module = import_module(match.group('module'))
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/lib/python3.12/importlib/__init__.py", line 90, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "<frozen importlib._bootstrap>", line 1387, in _gcd_import
  File "<frozen importlib._bootstrap>", line 1360, in _find_and_load
  File "<frozen importlib._bootstrap>", line 1331, in _find_and_load_unlocked
  File "<frozen importlib._bootstrap>", line 935, in _load_unlocked
  File "<frozen importlib._bootstrap_external>", line 999, in exec_module
  File "<frozen importlib._bootstrap>", line 488, in _call_with_frames_removed
  File "/content/CS598JBR-Team-9/MP1/human-eval/human_eval/evaluate_functional_correctness.py", line 28, in <module>
    sys.exit(main())
             ^^^^^^
  File "/content/CS598JBR-Team-9/MP1/human-eval/human_eval/evaluate_functional_correctness.py", line 25, in main
    fire.Fire(entry_point)
  File "/usr/local/lib/python3.12/dist-packages/fire/core.py", line 135, in Fire
    component_trace = _Fire(component, args, parsed_flag_args, context, name)
                      ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/fire/core.py", line 468, in _Fire
    component, remaining_args = _CallAndUpdateTrace(
                                ^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/fire/core.py", line 684, in _CallAndUpdateTrace
    component = fn(*varargs, **kwargs)
                ^^^^^^^^^^^^^^^^^^^^^^
  File "/content/CS598JBR-Team-9/MP1/human-eval/human_eval/evaluate_functional_correctness.py", line 20, in entry_point
    results = evaluate_functional_correctness(sample_file, k, n_workers, timeout, problem_file)
              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/content/CS598JBR-Team-9/MP1/human-eval/human_eval/evaluation.py", line 62, in evaluate_functional_correctness
    for sample in tqdm.tqdm(stream_jsonl(sample_file)):
                  ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.12/dist-packages/tqdm/std.py", line 1181, in __iter__
    for obj in iterable:
               ^^^^^^^^
  File "/content/CS598JBR-Team-9/MP1/human-eval/human_eval/data.py", line 26, in stream_jsonl
    with open(filename, "r") as fp:
         ^^^^^^^^^^^^^^^^^^^
FileNotFoundError: [Errno 2] No such file or directory: 'instruct_prompt_131515897657672734932032441166005753609.jsonl'
